// Requests are per 5 hours; allowances are monthly usage at official API prices.
export const goModels = [
  { id: "kimi-k3", name: "Kimi K3", requests: 110, allowance: 15, featured: true },
  { id: "qwen3.8-max", name: "Qwen3.8 Max", requests: 160, allowance: 15 },
  { id: "grok-4.6", name: "Grok 4.6", requests: 169, allowance: 15 },
  { id: "qwen3.7-max", name: "Qwen3.7 Max", requests: 170, allowance: 30 },
  { id: "glm-5.3", name: "GLM-5.3", requests: 220, allowance: 15 },
  { id: "glm-5.2", name: "GLM-5.2", requests: 880, allowance: 60 },
  { id: "glm-5.1", name: "GLM-5.1", requests: 880, allowance: 60 },
  { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", requests: 1050, allowance: 15 },
  { id: "kimi-k2.6", name: "Kimi K2.6", requests: 1150, allowance: 60 },
  { id: "kimi-k2.7-code", name: "Kimi K2.7 Code", requests: 1350, allowance: 60, featured: true },
  { id: "hy4-preview", name: "Hy4 preview", requests: 1350, allowance: 30 },
  { id: "gpt-5.6-luna", name: "GPT 5.6 Luna", requests: 2050, allowance: 15, featured: true },
  { id: "minimax-m3", name: "MiniMax M3", requests: 3200, allowance: 60, featured: true },
  { id: "mimo-v2.5-pro", name: "MiMo-V2.5-Pro", requests: 3250, allowance: 15 },
  { id: "qwen3.6-plus", name: "Qwen3.6 Plus", requests: 3300, allowance: 60 },
  { id: "minimax-m2.7", name: "MiniMax M2.7", requests: 3400, allowance: 60 },
  { id: "deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp", requests: 6500, allowance: 15 },
  { id: "qwen3.7-plus", name: "Qwen3.7 Plus", requests: 4300, allowance: 60, featured: true },
  { id: "hy3", name: "Hy3", requests: 4300, allowance: 60 },
  { id: "qwen3.8-flash", name: "Qwen3.8 Flash", requests: 5400, allowance: 30 },
  { id: "glm-5.3-flash", name: "GLM-5.3-Flash", requests: 6320, allowance: 60, featured: true },
  { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", requests: 13000, allowance: 30, featured: true },
  {
    id: "deepseek-flash",
    name: "DeepSeek V4.1 Flash",
    requests: 26000,
    baseRequests: 6500,
    allowance: 60,
    baseAllowance: 15,
    bonus: 4,
    featured: true,
    fresh: true,
  },
  { id: "longcat-2.0", name: "LongCat-2.0", requests: 11400, allowance: 60 },
  { id: "omen-alpha", name: "Omen Alpha", requests: 11600, allowance: 100, featured: true, fresh: true },
  { id: "mimo-v2.5", name: "MiMo-V2.5", requests: 30100, allowance: 60, featured: true },
  {
    id: "muse-spark-1.3-contributor",
    name: "Muse Spark 1.3 Contributor",
    requests: 45300,
    allowance: 60,
    featured: true,
    regions: true,
  },
  {
    id: "muse-spark-1.2-contributor",
    name: "Muse Spark 1.2 Contributor",
    requests: 45300,
    allowance: 60,
    regions: true,
  },
].sort((a, b) => a.requests - b.requests)
