// Generated from the Cargo.lock of each published BetterOffice engine and the license files of the published
// crate sources. Regenerate it when the @betteroffice packages update; do not edit it by hand.
export const crates = [
  {
    name: "adler2",
    version: "2.0.1",
    license: "0BSD OR MIT OR Apache-2.0",
    repository: "https://github.com/oyvindln/adler2",
    copyright: ["Copyright (c) Jonas Schievink, oyvindln"],
    texts: ["mit"],
  },
  {
    name: "allocator-api2",
    version: "0.2.21",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/zakarumych/allocator-api2",
    copyright: ["Copyright (c) Zakarum"],
    texts: ["mit"],
  },
  {
    name: "arc-swap",
    version: "1.9.2",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/vorner/arc-swap",
    copyright: ["Copyright (c) 2017 arc-swap developers"],
    texts: ["mit"],
  },
  {
    name: "arrayref",
    version: "0.3.9",
    license: "BSD-2-Clause",
    repository: "https://github.com/droundy/arrayref",
    copyright: ["Copyright (c) 2015 David Roundy <roundyd@physics.oregonstate.edu>"],
    texts: ["bsd-2-clause"],
  },
  {
    name: "arrayvec",
    version: "0.7.8",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/bluss/arrayvec",
    copyright: ['Copyright (c) Ulrik Sverdrup "bluss" 2015-2023'],
    texts: ["mit"],
  },
  {
    name: "async-lock",
    version: "3.4.2",
    license: "Apache-2.0 OR MIT",
    repository: "https://github.com/smol-rs/async-lock",
    copyright: ["Copyright (c) Stjepan Glavina"],
    texts: ["mit"],
  },
  {
    name: "base64",
    version: "0.22.1",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/marshallpierce/rust-base64",
    copyright: ["Copyright (c) 2015 Alice Maz"],
    texts: ["mit"],
  },
  {
    name: "bitflags",
    version: "2.13.0",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/bitflags/bitflags",
    copyright: ["Copyright (c) 2014 The Rust Project Developers"],
    texts: ["mit"],
  },
  {
    name: "block-buffer",
    version: "0.10.4",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/RustCrypto/utils",
    copyright: ["Copyright (c) 2018-2019 The RustCrypto Project Developers"],
    texts: ["mit"],
  },
  {
    name: "bytemuck",
    version: "1.25.1",
    license: "Zlib OR Apache-2.0 OR MIT",
    repository: "https://github.com/Lokathor/bytemuck",
    copyright: ['Copyright (c) 2019 Daniel "Lokathor" Gee.'],
    texts: ["mit-2"],
  },
  {
    name: "cfg-if",
    version: "1.0.4",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/rust-lang/cfg-if",
    copyright: ["Copyright (c) 2014 Alex Crichton"],
    texts: ["mit"],
  },
  {
    name: "concurrent-queue",
    version: "2.5.0",
    license: "Apache-2.0 OR MIT",
    repository: "https://github.com/smol-rs/concurrent-queue",
    copyright: ["Copyright (c) Stjepan Glavina, Taiki Endo, John Nunley"],
    texts: ["mit"],
  },
  {
    name: "core_maths",
    version: "0.1.1",
    license: "MIT",
    repository: "https://github.com/robertbastian/core_maths",
    copyright: ["Copyright (c) 2024 Robert Bastian"],
    texts: ["mit"],
  },
  {
    name: "crc32fast",
    version: "1.5.0",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/srijs/rust-crc32fast",
    copyright: ["Copyright (c) 2018 Sam Rijs, Alex Crichton and contributors"],
    texts: ["mit"],
  },
  {
    name: "crossbeam-utils",
    version: "0.8.22",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/crossbeam-rs/crossbeam",
    copyright: ["Copyright (c) 2019 The Crossbeam Project Developers"],
    texts: ["mit"],
  },
  {
    name: "crypto-common",
    version: "0.1.7",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/RustCrypto/traits",
    copyright: ["Copyright (c) 2021 RustCrypto Developers"],
    texts: ["mit"],
  },
  {
    name: "dashmap",
    version: "6.2.1",
    license: "MIT",
    repository: "https://github.com/xacrimon/dashmap",
    copyright: ["Copyright (c) 2019 Acrimon"],
    texts: ["mit"],
  },
  {
    name: "digest",
    version: "0.10.7",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/RustCrypto/traits",
    copyright: ["Copyright (c) 2017 Artyom Pavlov"],
    texts: ["mit"],
  },
  {
    name: "encoding_rs",
    version: "0.8.35",
    license: "(Apache-2.0 OR MIT) AND BSD-3-Clause",
    repository: "https://github.com/hsivonen/encoding_rs",
    copyright: ["Copyright Mozilla Foundation", "Copyright © WHATWG (Apple, Google, Mozilla, Microsoft)."],
    texts: ["mit", "bsd-3-clause"],
  },
  {
    name: "equivalent",
    version: "1.0.2",
    license: "Apache-2.0 OR MIT",
    repository: "https://github.com/indexmap-rs/equivalent",
    copyright: ["Copyright (c) 2016--2023"],
    texts: ["mit"],
  },
  {
    name: "event-listener-strategy",
    version: "0.5.4",
    license: "Apache-2.0 OR MIT",
    repository: "https://github.com/smol-rs/event-listener-strategy",
    copyright: ["Copyright (c) John Nunley"],
    texts: ["mit"],
  },
  {
    name: "event-listener",
    version: "5.4.1",
    license: "Apache-2.0 OR MIT",
    repository: "https://github.com/smol-rs/event-listener",
    copyright: ["Copyright (c) Stjepan Glavina, John Nunley"],
    texts: ["mit"],
  },
  {
    name: "fastrand",
    version: "2.4.1",
    license: "Apache-2.0 OR MIT",
    repository: "https://github.com/smol-rs/fastrand",
    copyright: ["Copyright (c) Stjepan Glavina"],
    texts: ["mit"],
  },
  {
    name: "fdeflate",
    version: "0.3.7",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/image-rs/fdeflate",
    copyright: ["Copyright (c) The image-rs Developers"],
    texts: ["mit"],
  },
  {
    name: "flate2",
    version: "1.1.9",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/rust-lang/flate2-rs",
    copyright: ["Copyright (c) 2014-2026 Alex Crichton"],
    texts: ["mit"],
  },
  {
    name: "foldhash",
    version: "0.2.0",
    license: "Zlib",
    repository: "https://github.com/orlp/foldhash",
    copyright: ["Copyright (c) 2024 Orson Peters"],
    texts: ["zlib"],
  },
  {
    name: "font-types",
    version: "0.12.1",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/googlefonts/fontations",
    copyright: ["Copyright (c) 2019 Fontations Developers"],
    texts: ["mit"],
  },
  {
    name: "futures-core",
    version: "0.3.32",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/rust-lang/futures-rs",
    copyright: ["Copyright (c) 2016 Alex Crichton", "Copyright (c) 2017 The Tokio Authors"],
    texts: ["mit"],
  },
  {
    name: "futures-task",
    version: "0.3.32",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/rust-lang/futures-rs",
    copyright: ["Copyright (c) 2016 Alex Crichton", "Copyright (c) 2017 The Tokio Authors"],
    texts: ["mit"],
  },
  {
    name: "futures-util",
    version: "0.3.32",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/rust-lang/futures-rs",
    copyright: ["Copyright (c) 2016 Alex Crichton", "Copyright (c) 2017 The Tokio Authors"],
    texts: ["mit"],
  },
  {
    name: "generic-array",
    version: "0.14.7",
    license: "MIT",
    repository: "https://github.com/fizyk20/generic-array",
    copyright: ["Copyright (c) 2015 Bartłomiej Kamiński"],
    texts: ["mit"],
  },
  {
    name: "getrandom",
    version: "0.3.4",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/rust-random/getrandom",
    copyright: [
      "Copyright (c) 2018-2025 The rust-random Project Developers",
      "Copyright (c) 2014 The Rust Project Developers",
    ],
    texts: ["mit"],
  },
  {
    name: "half",
    version: "2.7.1",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/VoidStarKat/half-rs",
    copyright: ["Copyright (c) Kathryn Long"],
    texts: ["mit"],
  },
  {
    name: "hashbrown",
    version: "0.14.5",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/rust-lang/hashbrown",
    copyright: ["Copyright (c) 2016 Amanieu d'Antras"],
    texts: ["mit"],
  },
  {
    name: "hashbrown",
    version: "0.17.1",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/rust-lang/hashbrown",
    copyright: ["Copyright (c) 2016 Amanieu d'Antras"],
    texts: ["mit"],
  },
  {
    name: "indexmap",
    version: "2.14.0",
    license: "Apache-2.0 OR MIT",
    repository: "https://github.com/indexmap-rs/indexmap",
    copyright: ["Copyright (c) 2016--2017"],
    texts: ["mit"],
  },
  {
    name: "itoa",
    version: "1.0.18",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/dtolnay/itoa",
    copyright: ["Copyright (c) David Tolnay"],
    texts: ["mit"],
  },
  {
    name: "js-sys",
    version: "0.3.103",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/wasm-bindgen/wasm-bindgen/tree/master/crates/js-sys",
    copyright: ["Copyright (c) 2014 Alex Crichton"],
    texts: ["mit"],
  },
  {
    name: "libm",
    version: "0.2.16",
    license: "MIT",
    repository: "https://github.com/rust-lang/compiler-builtins",
    copyright: [
      "Copyright (c) 2018 Jorge Aparicio",
      "Copyright © 2005-2020 Rich Felker, et al.",
      "Copyright © 1993,2004 Sun Microsystems",
      "Copyright © 2003-2011 David Schultz",
      "Copyright © 2003-2009 Steven G. Kargl",
      "Copyright © 2003-2009 Bruce D. Evans",
      "Copyright © 2008 Stephen L. Moshier",
      "Copyright © 2017-2018 Arm Limited",
    ],
    texts: ["mit-3"],
  },
  {
    name: "lock_api",
    version: "0.4.14",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/Amanieu/parking_lot",
    copyright: ["Copyright (c) 2016 The Rust Project Developers"],
    texts: ["mit"],
  },
  {
    name: "log",
    version: "0.4.33",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/rust-lang/log",
    copyright: ["Copyright (c) 2014 The Rust Project Developers"],
    texts: ["mit"],
  },
  {
    name: "memchr",
    version: "2.8.3",
    license: "Unlicense OR MIT",
    repository: "https://github.com/BurntSushi/memchr",
    copyright: ["Copyright (c) 2015 Andrew Gallant"],
    texts: ["mit"],
  },
  {
    name: "miniz_oxide",
    version: "0.8.9",
    license: "MIT OR Zlib OR Apache-2.0",
    repository: "https://github.com/Frommi/miniz_oxide/tree/master/miniz_oxide",
    copyright: [
      "Copyright 2013-2014 RAD Game Tools and Valve Software",
      "Copyright 2010-2014 Rich Geldreich and Tenacious Software LLC",
      "Copyright (c) 2017 Frommi",
      "Copyright (c) 2017-2024 oyvindln",
    ],
    texts: ["mit"],
  },
  {
    name: "once_cell",
    version: "1.21.4",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/matklad/once_cell",
    copyright: ["Copyright (c) Aleksey Kladov"],
    texts: ["mit"],
  },
  {
    name: "parking_lot_core",
    version: "0.9.12",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/Amanieu/parking_lot",
    copyright: ["Copyright (c) 2016 The Rust Project Developers"],
    texts: ["mit"],
  },
  {
    name: "pin-project-lite",
    version: "0.2.17",
    license: "Apache-2.0 OR MIT",
    repository: "https://github.com/taiki-e/pin-project-lite",
    copyright: ["Copyright (c) Taiki Endo"],
    texts: ["mit"],
  },
  {
    name: "png",
    version: "0.18.1",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/image-rs/image-png",
    copyright: ["Copyright (c) 2015 nwin"],
    texts: ["mit"],
  },
  {
    name: "quick-error",
    version: "2.0.1",
    license: "MIT OR Apache-2.0",
    repository: "http://github.com/tailhook/quick-error",
    copyright: ["Copyright (c) 2015 The quick-error Developers"],
    texts: ["mit"],
  },
  {
    name: "quick-xml",
    version: "0.41.0",
    license: "MIT",
    repository: "https://github.com/tafia/quick-xml",
    copyright: ["Copyright (c) 2016 Johann Tuffe"],
    texts: ["mit"],
  },
  {
    name: "read-fonts",
    version: "0.41.0",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/googlefonts/fontations",
    copyright: ["Copyright (c) 2019 Fontations Developers"],
    texts: ["mit"],
  },
  {
    name: "rustybuzz",
    version: "0.20.1",
    license: "MIT",
    repository: "https://github.com/harfbuzz/rustybuzz",
    copyright: ["Copyright (c) HarfBuzz developers", "Copyright (c) 2020 Yevhenii Reizner"],
    texts: ["mit"],
  },
  {
    name: "ryu-js",
    version: "1.0.3",
    license: "Apache-2.0 OR BSL-1.0",
    repository: "https://github.com/boa-dev/ryu-js",
    copyright: ["Copyright (c) David Tolnay, boa-dev"],
    texts: ["apache-2.0"],
  },
  {
    name: "scopeguard",
    version: "1.2.0",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/bluss/scopeguard",
    copyright: ['Copyright (c) 2016-2019 Ulrik Sverdrup "bluss" and scopeguard developers'],
    texts: ["mit"],
  },
  {
    name: "serde_core",
    version: "1.0.228",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/serde-rs/serde",
    copyright: ["Copyright (c) Erick Tryzelaar, David Tolnay"],
    texts: ["mit"],
  },
  {
    name: "serde_json",
    version: "1.0.150",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/serde-rs/json",
    copyright: ["Copyright (c) Erick Tryzelaar, David Tolnay"],
    texts: ["mit"],
  },
  {
    name: "serde",
    version: "1.0.228",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/serde-rs/serde",
    copyright: ["Copyright (c) Erick Tryzelaar, David Tolnay"],
    texts: ["mit"],
  },
  {
    name: "sha2",
    version: "0.10.9",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/RustCrypto/hashes",
    copyright: [
      "Copyright (c) 2006-2009 Graydon Hoare",
      "Copyright (c) 2009-2013 Mozilla Foundation",
      "Copyright (c) 2016 Artyom Pavlov",
    ],
    texts: ["mit"],
  },
  {
    name: "simd-adler32",
    version: "0.3.9",
    license: "MIT",
    repository: "https://github.com/mcountryman/simd-adler32",
    copyright: ["Copyright (c) [2021] [Marvin Countryman]"],
    texts: ["mit"],
  },
  {
    name: "skrifa",
    version: "0.44.0",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/googlefonts/fontations",
    copyright: ["Copyright (c) 2019 Fontations Developers"],
    texts: ["mit"],
  },
  {
    name: "slab",
    version: "0.4.12",
    license: "MIT",
    repository: "https://github.com/tokio-rs/slab",
    copyright: ["Copyright (c) 2019 Carl Lerche"],
    texts: ["mit"],
  },
  {
    name: "smallstr",
    version: "0.3.1",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/murarth/smallstr",
    copyright: ["Copyright (c) 2018-2020 Murarth"],
    texts: ["mit"],
  },
  {
    name: "smallvec",
    version: "1.15.2",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/servo/rust-smallvec",
    copyright: ["Copyright (c) 2018 The Servo Project Developers"],
    texts: ["mit"],
  },
  {
    name: "strict-num",
    version: "0.1.1",
    license: "MIT",
    repository: "https://github.com/RazrFalcon/strict-num",
    copyright: ["Copyright (c) 2022 Yevhenii Reizner"],
    texts: ["mit"],
  },
  {
    name: "thiserror",
    version: "2.0.18",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/dtolnay/thiserror",
    copyright: ["Copyright (c) David Tolnay"],
    texts: ["mit"],
  },
  {
    name: "tiff",
    version: "0.11.3",
    license: "MIT",
    repository: "https://github.com/image-rs/image-tiff",
    copyright: ["Copyright (c) 2018 PistonDevelopers"],
    texts: ["mit"],
  },
  {
    name: "tiny-skia-path",
    version: "0.12.0",
    license: "BSD-3-Clause",
    repository: "https://github.com/linebender/tiny-skia/tree/master/path",
    copyright: [
      "Copyright (c) 2011 Google Inc. All rights reserved.",
      "Copyright (c) 2020 Yevhenii Reizner All rights reserved.",
    ],
    texts: ["bsd-3-clause-2"],
  },
  {
    name: "tiny-skia",
    version: "0.12.0",
    license: "BSD-3-Clause",
    repository: "https://github.com/linebender/tiny-skia",
    copyright: [
      "Copyright (c) 2011 Google Inc. All rights reserved.",
      "Copyright (c) 2020 Yevhenii Reizner All rights reserved.",
    ],
    texts: ["bsd-3-clause-2"],
  },
  {
    name: "ttf-parser",
    version: "0.25.1",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/harfbuzz/ttf-parser",
    copyright: ["Copyright (c) 2018 Yevhenii Reizner"],
    texts: ["mit"],
  },
  {
    name: "typed-path",
    version: "0.12.3",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/chipsenkbeil/typed-path",
    copyright: ["Copyright (c) Chip Senkbeil"],
    texts: ["mit"],
  },
  {
    name: "typenum",
    version: "1.20.1",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/paholg/typenum",
    copyright: ["Copyright (c) 2014 Paho Lurie-Gregg"],
    texts: ["mit"],
  },
  {
    name: "unicode-bidi-mirroring",
    version: "0.4.0",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/RazrFalcon/unicode-bidi-mirroring",
    copyright: ["Copyright (c) 2020 Yevhenii Reizner"],
    texts: ["mit"],
  },
  {
    name: "unicode-bidi",
    version: "0.3.18",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/servo/unicode-bidi",
    copyright: ["Copyright (c) 2015 The Rust Project Developers"],
    texts: ["mit"],
  },
  {
    name: "unicode-ccc",
    version: "0.4.0",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/RazrFalcon/unicode-ccc",
    copyright: ["Copyright (c) 2020 Yevhenii Reizner"],
    texts: ["mit"],
  },
  {
    name: "unicode-ident",
    version: "1.0.24",
    license: "(MIT OR Apache-2.0) AND Unicode-3.0",
    repository: "https://github.com/dtolnay/unicode-ident",
    copyright: ["Copyright (c) David Tolnay", "Copyright © 1991-2023 Unicode, Inc."],
    texts: ["mit", "unicode-3.0"],
  },
  {
    name: "unicode-linebreak",
    version: "0.1.5",
    license: "Apache-2.0",
    repository: "https://github.com/axelf4/unicode-linebreak",
    copyright: ["Copyright (c) Axel Forsman"],
    texts: ["apache-2.0"],
  },
  {
    name: "unicode-properties",
    version: "0.1.4",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/unicode-rs/unicode-properties",
    copyright: ["Copyright (c) 2015 The Rust Project Developers"],
    texts: ["mit"],
  },
  {
    name: "unicode-script",
    version: "0.5.8",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/unicode-rs/unicode-script",
    copyright: ["Copyright (c) 2019 Manish Goregaokar"],
    texts: ["mit"],
  },
  {
    name: "unicode-segmentation",
    version: "1.13.3",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/unicode-rs/unicode-segmentation",
    copyright: ["Copyright (c) 2015 The Rust Project Developers"],
    texts: ["mit"],
  },
  {
    name: "wasm-bindgen-shared",
    version: "0.2.126",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/wasm-bindgen/wasm-bindgen/tree/master/crates/shared",
    copyright: ["Copyright (c) 2014 Alex Crichton"],
    texts: ["mit"],
  },
  {
    name: "wasm-bindgen",
    version: "0.2.126",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/wasm-bindgen/wasm-bindgen",
    copyright: ["Copyright (c) 2014 Alex Crichton"],
    texts: ["mit"],
  },
  {
    name: "weezl",
    version: "0.1.12",
    license: "MIT OR Apache-2.0",
    repository: "https://github.com/image-rs/weezl",
    copyright: ["Copyright (c) HeroicKatora 2020"],
    texts: ["mit"],
  },
  {
    name: "yrs",
    version: "0.27.3",
    license: "MIT",
    repository: "https://github.com/y-crdt/y-crdt/",
    copyright: ["Copyright (c) Kevin Jahns, Bartosz Sypytkowski"],
    texts: ["mit"],
  },
  {
    name: "zerocopy",
    version: "0.8.52",
    license: "BSD-2-Clause OR Apache-2.0 OR MIT",
    repository: "https://github.com/google/zerocopy",
    copyright: ["Copyright 2023 The Fuchsia Authors"],
    texts: ["mit"],
  },
  {
    name: "zip",
    version: "8.6.0",
    license: "MIT",
    repository: "https://github.com/zip-rs/zip2",
    copyright: ["Copyright (c) 2014 Mathijs van de Nes"],
    texts: ["mit"],
  },
  {
    name: "zlib-rs",
    version: "0.6.6",
    license: "Zlib",
    repository: "https://github.com/trifectatechfoundation/zlib-rs",
    copyright: ["(C) 2024 Trifecta Tech Foundation"],
    texts: ["zlib"],
  },
  {
    name: "zmij",
    version: "1.0.21",
    license: "MIT",
    repository: "https://github.com/dtolnay/zmij",
    copyright: ["Copyright (c) David Tolnay"],
    texts: ["mit"],
  },
]

export const crateTexts = [
  {
    id: "mit",
    license: "MIT",
    title: "MIT License",
    text: 'Permission is hereby granted, free of charge, to any\nperson obtaining a copy of this software and associated\ndocumentation files (the "Software"), to deal in the\nSoftware without restriction, including without\nlimitation the rights to use, copy, modify, merge,\npublish, distribute, sublicense, and/or sell copies of\nthe Software, and to permit persons to whom the Software\nis furnished to do so, subject to the following\nconditions:\n\nThe above copyright notice and this permission notice\nshall be included in all copies or substantial portions\nof the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF\nANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED\nTO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A\nPARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT\nSHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY\nCLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\nOF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR\nIN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\nDEALINGS IN THE SOFTWARE.',
  },
  {
    id: "mit-2",
    license: "MIT",
    title: "MIT License",
    text: 'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice (including the next paragraph) shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
  },
  {
    id: "mit-3",
    license: "MIT",
    title: "MIT License",
    text: 'rust-lang/libm as a whole is available for use under the MIT license:\n\n------------------------------------------------------------------------------\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the "Software"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n------------------------------------------------------------------------------\n\nAs a contributor, you agree that your code can be used under either the MIT\nlicense or the Apache-2.0 license:\n\n------------------------------------------------------------------------------\n                                 Apache License\n                           Version 2.0, January 2004\n                        http://www.apache.org/licenses/\n\n   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION\n\n   1. Definitions.\n\n      "License" shall mean the terms and conditions for use, reproduction,\n      and distribution as defined by Sections 1 through 9 of this document.\n\n      "Licensor" shall mean the copyright owner or entity authorized by\n      the copyright owner that is granting the License.\n\n      "Legal Entity" shall mean the union of the acting entity and all\n      other entities that control, are controlled by, or are under common\n      control with that entity. For the purposes of this definition,\n      "control" means (i) the power, direct or indirect, to cause the\n      direction or management of such entity, whether by contract or\n      otherwise, or (ii) ownership of fifty percent (50%) or more of the\n      outstanding shares, or (iii) beneficial ownership of such entity.\n\n      "You" (or "Your") shall mean an individual or Legal Entity\n      exercising permissions granted by this License.\n\n      "Source" form shall mean the preferred form for making modifications,\n      including but not limited to software source code, documentation\n      source, and configuration files.\n\n      "Object" form shall mean any form resulting from mechanical\n      transformation or translation of a Source form, including but\n      not limited to compiled object code, generated documentation,\n      and conversions to other media types.\n\n      "Work" shall mean the work of authorship, whether in Source or\n      Object form, made available under the License, as indicated by a\n      copyright notice that is included in or attached to the work\n      (an example is provided in the Appendix below).\n\n      "Derivative Works" shall mean any work, whether in Source or Object\n      form, that is based on (or derived from) the Work and for which the\n      editorial revisions, annotations, elaborations, or other modifications\n      represent, as a whole, an original work of authorship. For the purposes\n      of this License, Derivative Works shall not include works that remain\n      separable from, or merely link (or bind by name) to the interfaces of,\n      the Work and Derivative Works thereof.\n\n      "Contribution" shall mean any work of authorship, including\n      the original version of the Work and any modifications or additions\n      to that Work or Derivative Works thereof, that is intentionally\n      submitted to Licensor for inclusion in the Work by the copyright owner\n      or by an individual or Legal Entity authorized to submit on behalf of\n      the copyright owner. For the purposes of this definition, "submitted"\n      means any form of electronic, verbal, or written communication sent\n      to the Licensor or its representatives, including but not limited to\n      communication on electronic mailing lists, source code control systems,\n      and issue tracking systems that are managed by, or on behalf of, the\n      Licensor for the purpose of discussing and improving the Work, but\n      excluding communication that is conspicuously marked or otherwise\n      designated in writing by the copyright owner as "Not a Contribution."\n\n      "Contributor" shall mean Licensor and any individual or Legal Entity\n      on behalf of whom a Contribution has been received by Licensor and\n      subsequently incorporated within the Work.\n\n   2. Grant of Copyright License. Subject to the terms and conditions of\n      this License, each Contributor hereby grants to You a perpetual,\n      worldwide, non-exclusive, no-charge, royalty-free, irrevocable\n      copyright license to reproduce, prepare Derivative Works of,\n      publicly display, publicly perform, sublicense, and distribute the\n      Work and such Derivative Works in Source or Object form.\n\n   3. Grant of Patent License. Subject to the terms and conditions of\n      this License, each Contributor hereby grants to You a perpetual,\n      worldwide, non-exclusive, no-charge, royalty-free, irrevocable\n      (except as stated in this section) patent license to make, have made,\n      use, offer to sell, sell, import, and otherwise transfer the Work,\n      where such license applies only to those patent claims licensable\n      by such Contributor that are necessarily infringed by their\n      Contribution(s) alone or by combination of their Contribution(s)\n      with the Work to which such Contribution(s) was submitted. If You\n      institute patent litigation against any entity (including a\n      cross-claim or counterclaim in a lawsuit) alleging that the Work\n      or a Contribution incorporated within the Work constitutes direct\n      or contributory patent infringement, then any patent licenses\n      granted to You under this License for that Work shall terminate\n      as of the date such litigation is filed.\n\n   4. Redistribution. You may reproduce and distribute copies of the\n      Work or Derivative Works thereof in any medium, with or without\n      modifications, and in Source or Object form, provided that You\n      meet the following conditions:\n\n      (a) You must give any other recipients of the Work or\n          Derivative Works a copy of this License; and\n\n      (b) You must cause any modified files to carry prominent notices\n          stating that You changed the files; and\n\n      (c) You must retain, in the Source form of any Derivative Works\n          that You distribute, all copyright, patent, trademark, and\n          attribution notices from the Source form of the Work,\n          excluding those notices that do not pertain to any part of\n          the Derivative Works; and\n\n      (d) If the Work includes a "NOTICE" text file as part of its\n          distribution, then any Derivative Works that You distribute must\n          include a readable copy of the attribution notices contained\n          within such NOTICE file, excluding those notices that do not\n          pertain to any part of the Derivative Works, in at least one\n          of the following places: within a NOTICE text file distributed\n          as part of the Derivative Works; within the Source form or\n          documentation, if provided along with the Derivative Works; or,\n          within a display generated by the Derivative Works, if and\n          wherever such third-party notices normally appear. The contents\n          of the NOTICE file are for informational purposes only and\n          do not modify the License. You may add Your own attribution\n          notices within Derivative Works that You distribute, alongside\n          or as an addendum to the NOTICE text from the Work, provided\n          that such additional attribution notices cannot be construed\n          as modifying the License.\n\n      You may add Your own copyright statement to Your modifications and\n      may provide additional or different license terms and conditions\n      for use, reproduction, or distribution of Your modifications, or\n      for any such Derivative Works as a whole, provided Your use,\n      reproduction, and distribution of the Work otherwise complies with\n      the conditions stated in this License.\n\n   5. Submission of Contributions. Unless You explicitly state otherwise,\n      any Contribution intentionally submitted for inclusion in the Work\n      by You to the Licensor shall be under the terms and conditions of\n      this License, without any additional terms or conditions.\n      Notwithstanding the above, nothing herein shall supersede or modify\n      the terms of any separate license agreement you may have executed\n      with Licensor regarding such Contributions.\n\n   6. Trademarks. This License does not grant permission to use the trade\n      names, trademarks, service marks, or product names of the Licensor,\n      except as required for reasonable and customary use in describing the\n      origin of the Work and reproducing the content of the NOTICE file.\n\n   7. Disclaimer of Warranty. Unless required by applicable law or\n      agreed to in writing, Licensor provides the Work (and each\n      Contributor provides its Contributions) on an "AS IS" BASIS,\n      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or\n      implied, including, without limitation, any warranties or conditions\n      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A\n      PARTICULAR PURPOSE. You are solely responsible for determining the\n      appropriateness of using or redistributing the Work and assume any\n      risks associated with Your exercise of permissions under this License.\n\n   8. Limitation of Liability. In no event and under no legal theory,\n      whether in tort (including negligence), contract, or otherwise,\n      unless required by applicable law (such as deliberate and grossly\n      negligent acts) or agreed to in writing, shall any Contributor be\n      liable to You for damages, including any direct, indirect, special,\n      incidental, or consequential damages of any character arising as a\n      result of this License or out of the use or inability to use the\n      Work (including but not limited to damages for loss of goodwill,\n      work stoppage, computer failure or malfunction, or any and all\n      other commercial damages or losses), even if such Contributor\n      has been advised of the possibility of such damages.\n\n   9. Accepting Warranty or Additional Liability. While redistributing\n      the Work or Derivative Works thereof, You may choose to offer,\n      and charge a fee for, acceptance of support, warranty, indemnity,\n      or other liability obligations and/or rights consistent with this\n      License. However, in accepting such obligations, You may act only\n      on Your own behalf and on Your sole responsibility, not on behalf\n      of any other Contributor, and only if You agree to indemnify,\n      defend, and hold each Contributor harmless for any liability\n      incurred by, or claims asserted against, such Contributor by reason\n      of your accepting any such warranty or additional liability.\n\n   END OF TERMS AND CONDITIONS\n\n   APPENDIX: How to apply the Apache License to your work.\n\n      To apply the Apache License to your work, attach the following\n      boilerplate notice, with the fields enclosed by brackets "[]"\n      replaced with your own identifying information. (Don\'t include\n      the brackets!)  The text should be enclosed in the appropriate\n      comment syntax for the file format. We also recommend that a\n      file or class name and description of purpose be included on the\n      same "printed page" as the copyright notice for easier\n      identification within third-party archives.\n\n   Licensed under the Apache License, Version 2.0 (the "License");\n   you may not use this file except in compliance with the License.\n   You may obtain a copy of the License at\n\n       http://www.apache.org/licenses/LICENSE-2.0\n\n   Unless required by applicable law or agreed to in writing, software\n   distributed under the License is distributed on an "AS IS" BASIS,\n   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n   See the License for the specific language governing permissions and\n   limitations under the License.\n------------------------------------------------------------------------------\n\nThis Rust library contains the following copyrights:\n\n    Copyright (c) 2018 Jorge Aparicio\n\nPortions of this software are derived from third-party works licensed under\nterms compatible with the above MIT license:\n\n* musl libc https://www.musl-libc.org/. This library contains the following\n  copyright:\n\n      Copyright © 2005-2020 Rich Felker, et al.\n\n* The CORE-MATH project https://core-math.gitlabpages.inria.fr/. CORE-MATH\n  routines are available under the MIT license on a per-file basis.\n\nThe musl libc COPYRIGHT file also includes the following notice relevant to\nmath portions of the library:\n\n------------------------------------------------------------------------------\nMuch of the math library code (src/math/* and src/complex/*) is\nCopyright © 1993,2004 Sun Microsystems or\nCopyright © 2003-2011 David Schultz or\nCopyright © 2003-2009 Steven G. Kargl or\nCopyright © 2003-2009 Bruce D. Evans or\nCopyright © 2008 Stephen L. Moshier or\nCopyright © 2017-2018 Arm Limited\nand labelled as such in comments in the individual source files. All\nhave been licensed under extremely permissive terms.\n------------------------------------------------------------------------------\n\nCopyright notices are retained in src/* files where relevant.',
  },
  {
    id: "bsd-2-clause",
    license: "BSD-2-Clause",
    title: "BSD 2-Clause License",
    text: 'All rights reserved.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are\nmet:\n\n1. Redistributions of source code must retain the above copyright\n   notice, this list of conditions and the following disclaimer.\n\n2. Redistributions in binary form must reproduce the above copyright\n   notice, this list of conditions and the following disclaimer in the\n   documentation and/or other materials provided with the\n   distribution.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\nLIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\nA PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\nHOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\nDATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\nTHEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.',
  },
  {
    id: "bsd-3-clause",
    license: "BSD-3-Clause",
    title: "BSD 3-Clause License",
    text: 'Redistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are met:\n\n1. Redistributions of source code must retain the above copyright notice, this\n   list of conditions and the following disclaimer.\n\n2. Redistributions in binary form must reproduce the above copyright notice,\n   this list of conditions and the following disclaimer in the documentation\n   and/or other materials provided with the distribution.\n\n3. Neither the name of the copyright holder nor the names of its\n   contributors may be used to endorse or promote products derived from\n   this software without specific prior written permission.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"\nAND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\nIMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE\nFOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\nDAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR\nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\nCAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.',
  },
  {
    id: "bsd-3-clause-2",
    license: "BSD-3-Clause",
    title: "BSD 3-Clause License",
    text: 'Redistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are\nmet:\n\n  * Redistributions of source code must retain the above copyright\n    notice, this list of conditions and the following disclaimer.\n\n  * Redistributions in binary form must reproduce the above copyright\n    notice, this list of conditions and the following disclaimer in\n    the documentation and/or other materials provided with the\n    distribution.\n\n  * Neither the name of the copyright holder nor the names of its\n    contributors may be used to endorse or promote products derived\n    from this software without specific prior written permission.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\nLIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\nA PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\nOWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\nDATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\nTHEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.',
  },
  {
    id: "zlib",
    license: "Zlib",
    title: "zlib License",
    text: "This software is provided 'as-is', without any express or implied warranty. In\nno event will the authors be held liable for any damages arising from the use of\nthis software.\n\nPermission is granted to anyone to use this software for any purpose, including\ncommercial applications, and to alter it and redistribute it freely, subject to\nthe following restrictions:\n\n1. The origin of this software must not be misrepresented; you must not claim\n    that you wrote the original software. If you use this software in a product,\n    an acknowledgment in the product documentation would be appreciated but is\n    not required.\n\n2. Altered source versions must be plainly marked as such, and must not be\n    misrepresented as being the original software.\n\n3. This notice may not be removed or altered from any source distribution.",
  },
  {
    id: "unicode-3.0",
    license: "Unicode-3.0",
    title: "Unicode License v3",
    text: 'NOTICE TO USER: Carefully read the following legal agreement. BY\nDOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR\nSOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE\nTERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT\nDOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.\n\nPermission is hereby granted, free of charge, to any person obtaining a\ncopy of data files and any associated documentation (the "Data Files") or\nsoftware and any associated documentation (the "Software") to deal in the\nData Files or Software without restriction, including without limitation\nthe rights to use, copy, modify, merge, publish, distribute, and/or sell\ncopies of the Data Files or Software, and to permit persons to whom the\nData Files or Software are furnished to do so, provided that either (a)\nthis copyright and permission notice appear with all copies of the Data\nFiles or Software, or (b) this copyright and permission notice appear in\nassociated Documentation.\n\nTHE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY\nKIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF\nTHIRD PARTY RIGHTS.\n\nIN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE\nBE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,\nOR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,\nWHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,\nARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA\nFILES OR SOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder shall\nnot be used in advertising or otherwise to promote the sale, use or other\ndealings in these Data Files or Software without prior written\nauthorization of the copyright holder.',
  },
]
