import type { SymbolRole } from "./types"

export interface SymbolDefinition {
  value: string
  role?: SymbolRole
}

const ordinary: Record<string, string> = {
  alpha: "α",
  beta: "β",
  gamma: "γ",
  delta: "δ",
  epsilon: "ε",
  varepsilon: "ϵ",
  zeta: "ζ",
  eta: "η",
  theta: "θ",
  vartheta: "ϑ",
  iota: "ι",
  kappa: "κ",
  lambda: "λ",
  mu: "μ",
  nu: "ν",
  xi: "ξ",
  omicron: "ο",
  pi: "π",
  varpi: "ϖ",
  rho: "ρ",
  varrho: "ϱ",
  sigma: "σ",
  varsigma: "ς",
  tau: "τ",
  upsilon: "υ",
  phi: "ϕ",
  varphi: "φ",
  chi: "χ",
  psi: "ψ",
  omega: "ω",
  Gamma: "Γ",
  Delta: "Δ",
  Theta: "Θ",
  Lambda: "Λ",
  Xi: "Ξ",
  Pi: "Π",
  Sigma: "Σ",
  Upsilon: "Υ",
  Phi: "Φ",
  Psi: "Ψ",
  Omega: "Ω",
  infty: "∞",
  ell: "ℓ",
  hbar: "ℏ",
  imath: "ı",
  jmath: "ȷ",
  Re: "ℜ",
  Im: "ℑ",
  aleph: "ℵ",
  beth: "ℶ",
  gimel: "ℷ",
  daleth: "ℸ",
  partial: "∂",
  nabla: "∇",
  angle: "∠",
  measuredangle: "∡",
  triangle: "△",
  square: "□",
  lozenge: "◊",
  top: "⊤",
  bot: "⊥",
  emptyset: "∅",
  varnothing: "∅",
  forall: "∀",
  exists: "∃",
  nexists: "∄",
  neg: "¬",
  lnot: "¬",
  prime: "′",
  backprime: "‵",
  clubsuit: "♣",
  diamondsuit: "♢",
  heartsuit: "♡",
  spadesuit: "♠",
  checkmark: "✓",
}

const binary: Record<string, string> = {
  pm: "±",
  mp: "∓",
  times: "×",
  div: "÷",
  cdot: "·",
  ast: "∗",
  star: "⋆",
  circ: "∘",
  bullet: "∙",
  oplus: "⊕",
  ominus: "⊖",
  otimes: "⊗",
  oslash: "⊘",
  odot: "⊙",
  cap: "∩",
  cup: "∪",
  uplus: "⊎",
  sqcap: "⊓",
  sqcup: "⊔",
  vee: "∨",
  lor: "∨",
  wedge: "∧",
  land: "∧",
  setminus: "∖",
  wr: "≀",
  diamond: "⋄",
  bigtriangleup: "△",
  bigtriangledown: "▽",
  triangleleft: "◁",
  triangleright: "▷",
}

const relation: Record<string, string> = {
  equals: "=",
  neq: "≠",
  ne: "≠",
  equiv: "≡",
  approx: "≈",
  sim: "∼",
  simeq: "≃",
  cong: "≅",
  asymp: "≍",
  propto: "∝",
  lt: "<",
  gt: ">",
  le: "≤",
  leq: "≤",
  ge: "≥",
  geq: "≥",
  ll: "≪",
  gg: "≫",
  prec: "≺",
  succ: "≻",
  preceq: "⪯",
  succeq: "⪰",
  subset: "⊂",
  supset: "⊃",
  subseteq: "⊆",
  supseteq: "⊇",
  sqsubset: "⊏",
  sqsupset: "⊐",
  sqsubseteq: "⊑",
  sqsupseteq: "⊒",
  in: "∈",
  ni: "∋",
  notin: "∉",
  owns: "∋",
  vdash: "⊢",
  dashv: "⊣",
  models: "⊨",
  mid: "∣",
  parallel: "∥",
  perp: "⊥",
  smile: "⌣",
  frown: "⌢",
}

const arrows: Record<string, string> = {
  leftarrow: "←",
  gets: "←",
  rightarrow: "→",
  to: "→",
  leftrightarrow: "↔",
  Leftarrow: "⇐",
  Rightarrow: "⇒",
  Leftrightarrow: "⇔",
  mapsto: "↦",
  hookleftarrow: "↩",
  hookrightarrow: "↪",
  leftharpoonup: "↼",
  leftharpoondown: "↽",
  rightharpoonup: "⇀",
  rightharpoondown: "⇁",
  rightleftharpoons: "⇌",
  longleftarrow: "⟵",
  longrightarrow: "⟶",
  longleftrightarrow: "⟷",
  Longleftarrow: "⟸",
  Longrightarrow: "⟹",
  Longleftrightarrow: "⟺",
  longmapsto: "⟼",
  uparrow: "↑",
  downarrow: "↓",
  updownarrow: "↕",
  Uparrow: "⇑",
  Downarrow: "⇓",
  Updownarrow: "⇕",
  nearrow: "↗",
  searrow: "↘",
  swarrow: "↙",
  nwarrow: "↖",
}

const punctuation: Record<string, string> = {
  cdots: "⋯",
  ldots: "…",
  dots: "…",
  vdots: "⋮",
  ddots: "⋱",
  colon: ":",
}

export const symbolTable: Readonly<Record<string, SymbolDefinition>> = {
  ...Object.fromEntries(Object.entries(ordinary).map(([name, value]) => [name, { value, role: "ordinary" as const }])),
  ...Object.fromEntries(Object.entries(binary).map(([name, value]) => [name, { value, role: "binary" as const }])),
  ...Object.fromEntries(Object.entries(relation).map(([name, value]) => [name, { value, role: "relation" as const }])),
  ...Object.fromEntries(Object.entries(arrows).map(([name, value]) => [name, { value, role: "relation" as const }])),
  ...Object.fromEntries(
    Object.entries(punctuation).map(([name, value]) => [name, { value, role: "punctuation" as const }]),
  ),
}

export const largeOperators: Readonly<Record<string, string>> = {
  sum: "∑",
  prod: "∏",
  coprod: "∐",
  int: "∫",
  iint: "∬",
  iiint: "∭",
  oint: "∮",
  bigcap: "⋂",
  bigcup: "⋃",
  bigvee: "⋁",
  bigwedge: "⋀",
  bigoplus: "⨁",
  bigotimes: "⨂",
  bigodot: "⨀",
}

export const namedOperators = new Set([
  "arccos",
  "arcsin",
  "arctan",
  "arg",
  "cos",
  "cosh",
  "cot",
  "coth",
  "csc",
  "deg",
  "det",
  "dim",
  "exp",
  "gcd",
  "hom",
  "inf",
  "ker",
  "lg",
  "lim",
  "liminf",
  "limsup",
  "ln",
  "log",
  "max",
  "min",
  "mod",
  "Pr",
  "sec",
  "sin",
  "sinh",
  "sup",
  "tan",
  "tanh",
])

export const delimiterTable: Readonly<Record<string, string>> = {
  "(": "(",
  ")": ")",
  "[": "[",
  "]": "]",
  "\\{": "{",
  "\\}": "}",
  "{": "{",
  "}": "}",
  "|": "│",
  "\\|": "║",
  vert: "│",
  Vert: "║",
  lvert: "│",
  rvert: "│",
  lVert: "║",
  rVert: "║",
  lbrace: "{",
  rbrace: "}",
  langle: "⟨",
  rangle: "⟩",
  lfloor: "⌊",
  rfloor: "⌋",
  lceil: "⌈",
  rceil: "⌉",
  ".": "",
}

export const spacingCommands: Readonly<Record<string, number>> = {
  ",": 0,
  ":": 1,
  ";": 1,
  "!": 0,
  quad: 2,
  qquad: 4,
  enspace: 1,
  thinspace: 0,
}
